# Generated by Django 3.2.5 on 2021-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('laserSource', models.CharField(choices=[('Innolas Blizz', 'Innolas Blizz'), ('Eolite', 'Eolite'), ('CO2', 'CO2')], default='CO2', max_length=100)),
                ('image', models.ImageField(default='report.png', upload_to='report_pics')),
            ],
        ),
    ]
