# Generated by Django 3.2.5 on 2021-09-17 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='machine',
            field=models.CharField(choices=[('Divisio 9000', 'Divisio 9000'), ('Insignum 2000', 'Insignum 2000')], default='Divisio 9000', max_length=100),
        ),
    ]
