# Generated by Django 3.2.7 on 2021-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210917_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='laserSource',
        ),
        migrations.AddField(
            model_name='report',
            name='beamExpander',
            field=models.CharField(choices=[('8x motorized', '8x motorized')], default='8x motorized', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='beamSource',
            field=models.CharField(choices=[('Innolas Blizz', 'Innolas Blizz'), ('Eolite', 'Eolite'), ('CO2', 'CO2')], default='CO2', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='customerEmail',
            field=models.CharField(default='customer.company@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='customerId',
            field=models.CharField(default='BOS', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='customerName',
            field=models.CharField(default='Bosch', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='customerPlz',
            field=models.CharField(default=71332, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='customerStreet',
            field=models.CharField(default='Alte Landstrasse', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='customerTel',
            field=models.CharField(default='0711 1111111', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='lens',
            field=models.CharField(choices=[('255 mm f-theta', '255 mm f-theta')], default='255 mm f-theta', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='material',
            field=models.CharField(choices=[('FR4', 'FR4'), ('Kunststoff', 'Kunststoff'), ('V2A', 'V2A'), ('Aluminium', 'Aluminium'), ('Keramik', 'Keramik')], default='FR4', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='maxPower',
            field=models.CharField(default='40 W', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='microscope',
            field=models.CharField(choices=[('Keyence VHX-7100 Digital Microscope', 'Keyence VHX-7100 Digital Microscope')], default='Keyence VHX-7100 Digital Microscope', max_length=40),
        ),
        migrations.AddField(
            model_name='report',
            name='numberParts',
            field=models.CharField(default='10', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sampleHeigth',
            field=models.CharField(default='1.6', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sampleThickness',
            field=models.CharField(default='1.6', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sampleWidth',
            field=models.CharField(default='20', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='scanField',
            field=models.CharField(choices=[('100 x 100 mm^2', '100 x 100 mm^2'), ('150 x 150 mm^2', '150 x 150 mm^2'), ('180 x 180 mm^2', '180 x 180 mm^2')], default='100 x 100 mm^2', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='spotSize',
            field=models.CharField(default='50 um 1/e^2', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.CharField(choices=[('Laser depaneling', 'Laser depaneling'), ('Laser marking', 'Laser marking'), ('Laser engraving', 'Laser engraving')], default='Laser depaneling', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='wavelength',
            field=models.CharField(choices=[('1064 nm', '1064 nm'), ('532 nm', '532 nm'), ('265 nm', '265 nm')], default='532 nm', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='machine',
            field=models.CharField(choices=[('Divisio 9000', 'Divisio 9000'), ('Insignum 2000', 'Insignum 2000')], default='Divisio 9000', max_length=20),
        ),
    ]
