# Generated by Django 3.2.7 on 2021-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20210921_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, upload_to='media/pdfs'),
        ),
    ]
