# Generated by Django 3.2.7 on 2021-09-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image1',
            field=models.ImageField(blank=True, upload_to='report_pics'),
        ),
    ]
